apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ns-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 694900345478.dkr.ecr.ap-south-1.amazonaws.com/aws_eks_test_repo:f9126ce7649ba53d524493a2b881b549650a8674
          ports:
            - containerPort: 80
